name: yashuarts_new
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  url_launcher: ^6.3.0
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.5.0
  file_picker: ^10.3.1
  image_picker_for_web: ^2.2.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # Art images
    - assets/images/art_01.png
    - assets/images/art_02.png
    - assets/images/art_03.png
    - assets/images/art_04.png
    - assets/images/art_05.png
    - assets/images/art_06.png
    - assets/images/art_07.png
    - assets/images/art_08.png
    - assets/images/art_09.png
    - assets/images/art_10.png

    # Icons
    - assets/icons/app_logo.png
    - assets/icons/instagram.png
    - assets/icons/whatsapp.png
    - assets/backgrounds/home_screen_bg.png
    - assets/backgrounds/about_us_bg.png
    - assets/backgrounds/register_bg.jpeg
    
    # Animations
    - assets/animations/Sparkles.json
